### ISSUE TITLE
Read the article about the app migration

### ISSUE THREAD

**Issue by agudulin** [agudulin/today-is-not-your-birthday#5]
https://blog.chromium.org/2016/08/from-chrome-apps-to-web.html

**Comment by robinpokorny** [comment]
This change only affects apps, not extensions:

‘In the second half of 2017, the Chrome Web Store will no longer show Chrome apps on Windows, Mac, and Linux, but will **continue to surface extensions** and themes.’

**Comment by agudulin** [comment]
Thanks, @robinpokorny!
